apis/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from .views import BookDetail, BookList, BookInstanceDetail


urlpatterns = [
    path("auth/login", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh", TokenRefreshView.as_view(), name="token_refresh"),
    path("books", BookList.as_view()),
    path("books/create", BookDetail.as_view()),
    path("books/<int:pk>/update", BookDetail.as_view()),
    path("books/<uuid:pk>/renew", BookInstanceDetail.as_view()),
]

catalog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("book/", views.BookListView.as_view(), name="books"),
    path("book/<int:pk>/", views.BookDetailView.as_view(), name="book-detail"),
    path("mybooks/", views.LoanBookByUserListView.as_view(), name="my-borrowed"),
    path(
        "book/<uuid:pk>/renew/", views.renew_book_librarian, name="renew-book-librarian"
    ),
    path("author/create/", views.AuthorCreate.as_view(), name="author-create"),
    path("author/<int:pk>/update/", views.AuthorUpdate.as_view(), name="author-update"),
    path("author/<int:pk>/delete/", views.AuthorDelete.as_view(), name="author-delete"),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
    path("", RedirectView.as_view(url="catalog/")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("api/", include("apis.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date

from django.utils.translation import gettext_lazy as _
from .utils.constants import LOAN_STATUS


# Create your models here.


class Genre(models.Model):
    """Model representing a book genre."""

    name = models.CharField(max_length=200, help_text=_("Enter your book genre"))

    def __str__(self):
        """Return name of Genre objects"""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""

    title = models.CharField(max_length=200)
    author = models.ForeignKey("Author", on_delete=models.SET_NULL, null=True)
    """on_delete option:
    - CASCADE
    - PROTECT
    - RESTRICT
    - SET_DEFAULT
    - SET
    - DO_NOTHING
    """

    summary = models.TextField(max_length=1000, help_text=_("Enter your summary"))
    isbn = models.CharField(
        "ISBN",
        max_length=13,
        unique=True,
        help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
    )

    genre = models.ManyToManyField(Genre, help_text=_("Select a genre for this book"))

    def __str__(self):
        """Return title of book objects"""
        return self.title

    def get_absolute_url(self):
        """Returns a URL for displaying individual model records on the website"""
        return reverse("book-detail", args=[str(self.id)])

    def display_genre(self):
        return ", ".join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = "Genre"


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="Unique ID for this particular bookacross whole library",
    )
    book = models.ForeignKey("Book", on_delete=models.RESTRICT)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default="m",
        help_text="Book availability",
    )

    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        """Declare model-level metadata for Model"""

        # Books are ordered by 'due_back' value by default
        ordering = ["due_back"]
        permissions = (("can_mark_as_returned", "Set book as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return f"{self.id} ({self.book.title})"

    @property
    def is_overdue(self):
        return self.due_back and date.today() > self.due_back


class Author(models.Model):
    """Model representing an author."""

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField("Died", null=True, blank=True)

    class Meta:
        # Author are ordered by 'last_name' and 'fist_name' by default
        ordering = ["last_name", "first_name"]

    def get_absolute_url(self):
        """Returns a URL for displaying individual model records on the website"""
        return reverse("author-detail", args=[str(self.id)])

    def __str__(self):
        """Return string representing last name and first name of Author objects"""
        return f"{self.last_name}, {self.first_name}"

catalog/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404
from catalog.models import Book, BookInstance, Genre, Author
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from .form import RenewBookForm
import datetime
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, permission_required

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from catalog.models import Author

# Create your views here.


def index(request):
    """View function for home page of site"""

    # Generate counts of some of the main object

    num_books = Book.objects.count()
    num_instances = BookInstance.objects.count()

    num_instances_available = BookInstance.objects.filter(status="a").count()

    num_authors = Author.objects.count()

    num_visits = request.session.get("num_visits", 1)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_books": num_books,
        "num_instances": num_instances,
        "num_instances_available": num_instances_available,
        "num_authors": num_authors,
        "num_visits": num_visits,
    }

    return render(request, "index.html", context=context)


class BookListView(generic.ListView):
    model = Book
    queryset = Book.objects.filter(title__icontains="Doraemon")[:5]
    context_object_name = "book_list"
    template_name = "catalog/book_list.html"


class BookDetailView(generic.DetailView):
    model = Book


class LoanBookByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance

    queryset = BookInstance.objects.filter(status="o")
    context_object_name = "bookinstance_list"
    template_name = "catalog/bookinstance_list_borrowed_user.html"


def book_detail_view(request, primary_key):
    book = get_object_or_404(Book, pk=primary_key)

    return render(request, "catalog/book_detail.html", context={"book": book})


@login_required
@permission_required("catalog.can_mark_returned", raise_exception=True)
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)
    form = RenewBookForm()

    # If this is a POST request then process the Form data
    if request.method == "POST":
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the modeldue_back field)
            book_instance.due_back = form.cleaned_data["renewal_date"]
            book_instance.save()
            return HttpResponseRedirect(reverse("all-borrowed"))

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={"renewal_date": proposed_renewal_date})

    context = {
        "form": form,
        "book_instance": book_instance,
    }
    return render(request, "catalog/book_renew_librarian.html", context)


class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    fields = ["first_name", "last_name", "date_of_birth", "date_of_death"]
    initial = {"date_of_death": "11/06/2020"}
    permission_required = "catalog.add_author"


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = ["first_name", "last_name", "date_of_birth", "date_of_death"]
    permission_required = "catalog.change_author"


class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy("authors")
    permission_required = "catalog.delete_author"

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
  <h1>{% translate "Delete Author" %}</h1>
  <p> {% translate "Are you sure you want to delete the author:" %} {{ author }}?</p>
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
  </form>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
<h1>{% translate "Title:" %} {{ book.title }}</h1>
<p><strong>{% translate "Author:" %}</strong> <a href="">{{ book.author }}</a></p>
 <!-- author detail linknot yet defined -->
 <p><strong>{% translate "Summary:" %}</strong> {{ book.summary }}</p>
 <p><strong>{% translate "ISBN:" %}</strong> {{ book.isbn }}</p>
 <p><strong>{% translate "Language:" %}</strong> {{ book.language }}</p>
 <p><strong>{% translate "Genre:" %}</strong> {{ book.genre.all|join:", " }}</p>
 <div style="margin-left:20px;margin-top:20px">
  <h4>{% translate "Copies" %}</h4>
  {% for copy in book.bookinstance_set.all %}
  <hr>
  <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm'%}text-danger{% else %}text-warning{% endif %}">
    {{ copy.get_status_display }}
  </p>
  {% if copy.status != 'a' %}
    <p><strong>{% translate "Due to be returned:" %}</strong> {{ copy.due_back }}</p>
  {% endif %}
    <p><strong>{% translate "Imprint:" %}</strong> {{ copy.imprint }}</p>
    <p class="text-muted"><strong>{% translate "Id:" %}</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}
{% load i18n %}


{% block content %}
  <h1>{% translate "Book List" %}</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
    <li><a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})</li>
    {% endfor %}
  </ul>
  {% else %}
  <p>{% translate "There are no books in the library." %}</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
  <h1>{% translate "Renew:" %} {{ book_instance.book.title }}</h1>
  <p>{% translate "Borrower:" %} {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>{% translate "Due date:" %}{{book_instance.due_back }}</p>
  <form action="" method="post">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
  <h1>{% translate "Borrowed books" %}</h1>
  {% if bookinstance_list %}
    <ul>
      {% for bookinst in bookinstance_list %}
        <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
          <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{bookinst.due_back }})
          {% if perms.catalog.can_mark_returned %} 
            <a href="{% url 'renew-book-librarian' bookinst.id %}">{% translate "Renew" %}</a>
          {% endif %}
        </li>
          
      {% endfor %}
    </ul>
  {% else %}
    <p>{% translate "There are no books borrowed." %}</p>
  {% endif %}
{% endblock %}